var courses = [
  {
    "name": "Marketing",
    "courses": 17,
    "image": "marketing.png",
    "title": "Solve Maketing",
    "views": "12k",
    "rating": 4.5,
    "price": 60,
    "persentDiscout": 10,
  },
  {
    "name": "UX Design",
    "courses": 20,
    "image": "ux_design.png",
    "title": "Design UX",
    "views": "19k",
    "rating": 4.9,
    "price": 90,
    "persentDiscout": 20,
  },
  {
    "name": "Photography",
    "courses": 13,
    "image": "photography.png",
    "title": "Attract Photo",
    "views": "15k",
    "rating": 4.2,
    "price": 70,
    "persentDiscout": 15,
  },
  {
    "name": "Business",
    "courses": 17,
    "image": "business.png",
    "title": "Efficient Working",
    "views": "10k",
    "rating": 4.0,
    "price": 45,
    "persentDiscout": 10,
  },
];
